dic = {
            'RPG':"RPG",
            '冒険':'bouken',
            'イス':"isu",
            '消しゴム':"kesigomu",
            '焼肉':"yainiku",
            '鏡':"kagami",
            'お金':"okane",
            'ネクタイ':"nekutai",
            '傘':"kasa",
            'ゴミ':"gomi",
            'マクラ':"makura",
            '電気':"dennki",
            'マウス':"mausu",
            '教科書':"kyoukasyo",
            'うちわ':"uchiwa",
            '帽子':"boushi",
            '筆箱':'fudebako'            
        }